services:
  - type: web
    name: lunch-expense-app
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python migrate_category.py && gunicorn app:app
    envVars:
      - key: SECRET_KEY
        generateValue: true
  - type: worker
    name: lunch-expense-telegram-bot
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python telegram_bot.py
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: DATABASE_URL
        sync: false
